require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7
  TargetRailsVersion: 6.1
  Exclude:
    - 'Gemfile'
    - 'Rakefile'
    - 'config.ru'
    - 'bin/*'
    - 'config/**/*'
    - 'node_modules/**/*'
    - 'lib/tasks/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'db/schema.rb'
    - 'vendor/**/*'

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space # default is space

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Max: 15
  Exclude:
    - 'db/migrate/*'

RSpec/NestedGroups:
  Enabled: false
